#!/bin/bash

set -e  # Exit immediately if a command exits with a non-zero status.
set -x  # All executed commands are printed to the terminal

aptitude update ; aptitude install -y build-essential postgresql-plpython3-15 python3-all-dev python3-pip
service postgresql start
su - postgres -c "psql -c \"CREATE EXTENSION plpython3u;\""
su - postgres -c "psql -d template1 -c \"CREATE EXTENSION plpython3u;\""
service postgresql stop

# wget -O "/tmp/get-pip.py" "https://bootstrap.pypa.io/get-pip.py"
# python3 /tmp/get-pip.py

apt-get -y autoremove ; aptitude -y autoclean ; apt-get -y autoclean
rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/* /root/.aptitude /root/.wget-hsts /root/.cache

