#!/bin/bash

set -e  # Exit immediately if a command exits with a non-zero status.
set -x  # All executed commands are printed to the terminal

gpg --no-default-keyring --keyring /tmp/temp.keyring --keyserver keyserver.ubuntu.com --recv-keys 7FCC7D46ACCC4CF8
gpg -o /etc/apt/keyrings/postgresql.gpg --export --no-default-keyring --keyring /tmp/temp.keyring
echo "deb [signed-by=/etc/apt/keyrings/postgresql.gpg] http://apt.postgresql.org/pub/repos/apt bookworm-pgdg main" > /etc/apt/sources.list.d/postgresql.list
echo -e "Package: *\nPin: release o=apt.postgresql.org\nPin-Priority: -900\n" > /etc/apt/preferences.d/postgresql

# Create the user 'postgres' with uid 1000
adduser --uid 1000 --disabled-password --shell=/bin/bash --gecos "PostgreSQL administrator" --no-create-home --home /var/lib/postgresql postgres

aptitude update ; aptitude install -y postgresql-15 phppgadmin
service postgresql start
su - postgres -c "psql -c \"alter user postgres with password 'postgres';\""
service postgresql stop

# PostgreSQL listens on all networks
sed -i "59d" /etc/postgresql/15/main/postgresql.conf
sed -i "59ilisten_addresses = '*'\t\t\t# what IP address(es) to listen on;" /etc/postgresql/15/main/postgresql.conf
sed -i "92d" /etc/postgresql/15/main/pg_hba.conf
sed -i "92ihost    all             all             0.0.0.0/0               md5" /etc/postgresql/15/main/pg_hba.conf

# Enable login with user 'postgres' in phpPgAdmin
sed -i "s/conf\['extra_login_security'\] = true/conf['extra_login_security'] = false/" /usr/share/phppgadmin/conf/config.inc.php

# Fix phpPgAdmin to make it work with PostgreSQL 15
sed -i "79i\            case '15': return 'Postgres';break;" /usr/share/phppgadmin/classes/database/Connection.php

# Enable access to phpPgAdmin from anywhere
sed -i 's/Require/# Require/' /etc/apache2/conf-enabled/phppgadmin.conf

apt-get -y autoremove ; aptitude -y autoclean ; apt-get -y autoclean
rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/* /root/.aptitude
