name: Docker PostgreSQL

on:
  workflow_dispatch:
  repository_dispatch:
    types: [debian-updated]

env:
  REGISTRY: ghcr.io

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - 
        name: Build and push Docker images
        uses: docker/build-push-action@v2.7.0
        with:
          context: Base
          file: Base/Dockerfile
          push: true
          tags: ${{ env.REGISTRY }}/${{ github.actor }}/postgresql:latest,
                ${{ env.REGISTRY }}/${{ github.actor }}/postgresql:base
      - 
        name: Build and push Docker images
        uses: docker/build-push-action@v2.7.0
        with:
          context: Python
          file: Python/Dockerfile
          push: true
          tags: ${{ env.REGISTRY }}/${{ github.actor }}/postgresql:python
